services:
  - type: worker
    name: rajasthan-exam-info-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_PATH
        value: data/raj_exam_bot.sqlite3
      - key: PYTHON_VERSION
        value: 3.12.3
